<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import api from '../../services/api'
interface Category { id:number; name:string }
interface Expense { id:number; concept:string; description:string; amount:number; expense_date:string; status:'Pagado'|'Pendiente'; category_id?:number|null; category_name?:string|null }
const props=defineProps<{monthCode:string}>(); const emit=defineEmits<{(e:'refresh'):void}>()
const expenses=ref<Expense[]>([]),categories=ref<Category[]>([]),open=ref(false),editing=ref<number|null>(null)
const form=ref({concept:'',description:'',amount:0,expense_date:'',category_id:null as number|null})
const total=computed(()=>expenses.value.reduce((s,x)=>s+x.amount,0));const paid=computed(()=>expenses.value.filter(x=>x.status==='Pagado').reduce((s,x)=>s+x.amount,0));const pending=computed(()=>total.value-paid.value)
const load=async()=>{const [a,b]=await Promise.all([api.get(`/extra-expenses/${props.monthCode}`),api.get('/extra-expense-categories')]);expenses.value=a.data;categories.value=b.data}
const reset=()=>{editing.value=null;form.value={concept:'',description:'',amount:0,expense_date:`${props.monthCode}-01`,category_id:null};open.value=false}
const save=async()=>{if(editing.value===null)await api.post(`/extra-expenses?month_code=${props.monthCode}`,form.value);else await api.patch(`/extra-expenses/${editing.value}`,form.value);await load();emit('refresh');reset()}
const edit=(x:Expense)=>{editing.value=x.id;form.value={concept:x.concept,description:x.description,amount:x.amount,expense_date:x.expense_date,category_id:x.category_id||null};open.value=true}
const remove=async(x:Expense)=>{if(confirm(`¿Eliminar "${x.concept}"?`)){await api.delete(`/extra-expenses/${x.id}`);await load();emit('refresh')}}
const toggle=async(x:Expense)=>{await api.patch(`/extra-expenses/${x.id}/status`,{status:x.status==='Pagado'?'Pendiente':'Pagado'});await load();emit('refresh')}
watch(()=>props.monthCode,()=>{reset();load()});onMounted(()=>{reset();load()})
</script>
<template><section class="card"><header><div><h3>Extras y Compras</h3><p>Gastos puntuales de {{monthCode}}</p></div><button class="primary" @click="open?reset():open=true">{{open?'Cancelar':'+ Añadir gasto'}}</button></header><form v-if="open" @submit.prevent="save"><input v-model.trim="form.concept" required placeholder="Nombre"/><input v-model.trim="form.description" placeholder="Descripción"/><input v-model.number="form.amount" required min=".01" step=".01" type="number"/><input v-model="form.expense_date" required type="date"/><select v-model="form.category_id"><option :value="null">Sin categoría</option><option v-for="c in categories" :value="c.id">{{c.name}}</option></select><button class="primary">Guardar</button></form><div class="metrics"><div>Previsto<b>{{total.toFixed(2)}} €</b></div><div>Pagado<b class="green">{{paid.toFixed(2)}} €</b></div><div>Pendiente<b class="orange">{{pending.toFixed(2)}} €</b></div></div><div class="list"><article v-for="x in expenses" :key="x.id"><button :class="['state',x.status==='Pagado'?'paid':'wait']" @click="toggle(x)">{{x.status==='Pagado'?'✓ Pagado':'Pendiente'}}</button><div class="info"><b>{{x.concept}}</b><span v-if="x.description">{{x.description}}</span><small>{{new Date(`${x.expense_date}T12:00:00`).toLocaleDateString('es-ES')}} · {{x.category_name||'Sin categoría'}}</small></div><b>{{x.amount.toFixed(2)}} €</b><div class="actions"><button @click="edit(x)">Editar</button><button class="danger" @click="remove(x)">Eliminar</button></div></article><p v-if="!expenses.length">No hay gastos extra este mes.</p></div></section></template>
<style scoped>.card{background:#fff;padding:24px;border:1px solid var(--border-color);border-radius:12px}header,article,.metrics,form{display:flex;align-items:center;gap:12px}header{justify-content:space-between}h3,p{margin:0}header p,small,.info span{color:var(--text-muted);font-size:.85rem}.primary{border:0;border-radius:8px;padding:10px 14px;background:var(--primary);color:#fff;font-weight:700;cursor:pointer}form{margin:18px 0;padding:14px;background:#f8fafc;border-radius:9px}input,select{min-width:0;flex:1;padding:8px;border:1px solid var(--border-color);border-radius:7px}.metrics{margin:18px 0;border:1px solid var(--border-color);border-radius:10px;overflow:hidden}.metrics div{flex:1;padding:12px;color:var(--text-muted);border-right:1px solid var(--border-color)}.metrics div:last-child{border:0}.metrics b{display:block;color:var(--text-main);font-size:1.05rem;margin-top:5px}.green{color:#16a34a!important}.orange{color:#b45309!important}.list{border-top:1px solid var(--border-color)}article{padding:14px 4px;border-bottom:1px solid var(--border-color)}.state{border:0;border-radius:999px;padding:7px 13px;min-width:96px;font-weight:700;cursor:pointer}.paid{background:#dcfce7;color:#15803d}.wait{background:#fef3c7;color:#b45309}.info{flex:1;display:flex;flex-direction:column;gap:3px}.actions{display:flex;gap:9px}.actions button{border:0;background:none;color:var(--primary);font-weight:700;cursor:pointer}.actions .danger{color:#dc2626}@media(max-width:800px){form,article{flex-wrap:wrap}.info{min-width:55%}}</style>
